---
image: whoa
script:
  - /home/ubuntu/virtualenv/python2.4/bin/python -V
  - /home/ubuntu/virtualenv/python2.5/bin/python -V
  - /home/ubuntu/virtualenv/python2.6/bin/python -V
  - /home/ubuntu/virtualenv/python2.7/bin/python -V
  - /home/ubuntu/virtualenv/python3.1/bin/python -V
  - /home/ubuntu/virtualenv/python3.2/bin/python -V
  - /home/ubuntu/virtualenv/python3.3/bin/python -V
  - while true; do sleep 2; done;
